import { Customer, Interaction, Opportunity } from './types'

export const mockOpportunities: Opportunity[] = [
  {
    id: 'op-1',
    title: 'Licença Anual - Plano Enterprise',
    estimatedValue: 15000,
    customerName: 'TechCorp',
    stage: 'Qualificação',
    createdAt: '2023-10-02T10:00:00Z',
  },
  {
    id: 'op-2',
    title: 'Consultoria de Implantação',
    estimatedValue: 5000,
    customerName: 'Inovação TI',
    stage: 'Proposta',
    createdAt: '2023-10-06T14:30:00Z',
  },
  {
    id: 'op-3',
    title: 'Renovação de Contrato 2024',
    estimatedValue: 12000,
    customerName: 'Varejo Plus',
    stage: 'Negociação',
    createdAt: '2023-10-11T09:15:00Z',
  },
  {
    id: 'op-4',
    title: 'Pacote de Treinamento',
    estimatedValue: 3500,
    customerName: 'Startup Alpha',
    stage: 'Prospecção',
    createdAt: '2023-10-13T16:20:00Z',
  },
  {
    id: 'op-5',
    title: 'Projeto Customizado',
    estimatedValue: 25000,
    customerName: 'Construtora Base',
    stage: 'Fechado/Ganho',
    createdAt: '2023-08-20T08:30:00Z',
  },
]

export const mockCustomers: Customer[] = [
  {
    id: '1',
    name: 'Ana Silva',
    email: 'ana.silva@techcorp.com.br',
    phone: '(11) 98765-4321',
    company: 'TechCorp',
    status: 'Ativo',
    avatar: 'https://img.usecurling.com/ppl/thumbnail?gender=female&seed=1',
    createdAt: '2023-10-01T10:00:00Z',
  },
  {
    id: '2',
    name: 'Carlos Mendes',
    email: 'carlos@inovacao.net',
    phone: '(21) 97654-3210',
    company: 'Inovação TI',
    status: 'Lead',
    avatar: 'https://img.usecurling.com/ppl/thumbnail?gender=male&seed=2',
    createdAt: '2023-10-05T14:30:00Z',
  },
  {
    id: '3',
    name: 'Beatriz Costa',
    email: 'beatriz.costa@vendas.com',
    phone: '(31) 99887-6655',
    company: 'Varejo Plus',
    status: 'Ativo',
    avatar: 'https://img.usecurling.com/ppl/thumbnail?gender=female&seed=3',
    createdAt: '2023-10-10T09:15:00Z',
  },
  {
    id: '4',
    name: 'Fernando Rocha',
    email: 'fernando@logistica.br',
    phone: '(41) 98877-6655',
    company: 'Logística Express',
    status: 'Inativo',
    avatar: 'https://img.usecurling.com/ppl/thumbnail?gender=male&seed=4',
    createdAt: '2023-09-20T11:45:00Z',
  },
  {
    id: '5',
    name: 'Mariana Souza',
    email: 'mariana.souza@startup.co',
    phone: '(51) 97766-5544',
    company: 'Startup Alpha',
    status: 'Lead',
    avatar: 'https://img.usecurling.com/ppl/thumbnail?gender=female&seed=5',
    createdAt: '2023-10-12T16:20:00Z',
  },
  {
    id: '6',
    name: 'Roberto Alves',
    email: 'roberto@construtora.com',
    phone: '(61) 96655-4433',
    company: 'Construtora Base',
    status: 'Ativo',
    avatar: 'https://img.usecurling.com/ppl/thumbnail?gender=male&seed=6',
    createdAt: '2023-08-15T08:30:00Z',
  },
]

export const mockInteractions: Interaction[] = [
  {
    id: '1',
    customerId: '1',
    type: 'call',
    date: '2023-10-15T14:30:00Z',
    description: 'Ligação realizada para apresentar nova proposta comercial.',
  },
  {
    id: '2',
    customerId: '1',
    type: 'email',
    date: '2023-10-14T09:00:00Z',
    description: 'E-mail enviado com o material de apresentação e cases de sucesso.',
  },
  {
    id: '3',
    customerId: '1',
    type: 'note',
    date: '2023-10-10T11:00:00Z',
    description: 'Cliente demonstrou interesse no plano anual.',
  },
  {
    id: '4',
    customerId: '2',
    type: 'meeting',
    date: '2023-10-16T10:00:00Z',
    description: 'Reunião de alinhamento sobre as necessidades técnicas.',
  },
  {
    id: '5',
    customerId: '2',
    type: 'call',
    date: '2023-10-12T15:20:00Z',
    description: 'Primeiro contato realizado. Agendada reunião de discovery.',
  },
  {
    id: '6',
    customerId: '3',
    type: 'email',
    date: '2023-10-12T09:30:00Z',
    description: 'Enviada fatura referente à renovação do contrato.',
  },
  {
    id: '7',
    customerId: '4',
    type: 'note',
    date: '2023-09-25T14:15:00Z',
    description: 'Cliente solicitou cancelamento temporário do serviço.',
  },
  {
    id: '8',
    customerId: '5',
    type: 'meeting',
    date: '2023-10-15T16:00:00Z',
    description: 'Apresentação da plataforma para o time de operações.',
  },
  {
    id: '9',
    customerId: '6',
    type: 'call',
    date: '2023-09-10T10:45:00Z',
    description: 'Acompanhamento do uso da ferramenta após o primeiro mês.',
  },
]
