import { Customer } from './types'

export const mockCustomers: Customer[] = [
  {
    id: '1',
    name: 'Ana Silva',
    email: 'ana.silva@techcorp.com.br',
    phone: '(11) 98765-4321',
    company: 'TechCorp',
    status: 'Ativo',
    avatar: 'https://img.usecurling.com/ppl/thumbnail?gender=female&seed=1',
    createdAt: '2023-10-01T10:00:00Z',
  },
  {
    id: '2',
    name: 'Carlos Mendes',
    email: 'carlos@inovacao.net',
    phone: '(21) 97654-3210',
    company: 'Inovação TI',
    status: 'Lead',
    avatar: 'https://img.usecurling.com/ppl/thumbnail?gender=male&seed=2',
    createdAt: '2023-10-05T14:30:00Z',
  },
  {
    id: '3',
    name: 'Beatriz Costa',
    email: 'beatriz.costa@vendas.com',
    phone: '(31) 99887-6655',
    company: 'Varejo Plus',
    status: 'Ativo',
    avatar: 'https://img.usecurling.com/ppl/thumbnail?gender=female&seed=3',
    createdAt: '2023-10-10T09:15:00Z',
  },
  {
    id: '4',
    name: 'Fernando Rocha',
    email: 'fernando@logistica.br',
    phone: '(41) 98877-6655',
    company: 'Logística Express',
    status: 'Inativo',
    avatar: 'https://img.usecurling.com/ppl/thumbnail?gender=male&seed=4',
    createdAt: '2023-09-20T11:45:00Z',
  },
  {
    id: '5',
    name: 'Mariana Souza',
    email: 'mariana.souza@startup.co',
    phone: '(51) 97766-5544',
    company: 'Startup Alpha',
    status: 'Lead',
    avatar: 'https://img.usecurling.com/ppl/thumbnail?gender=female&seed=5',
    createdAt: '2023-10-12T16:20:00Z',
  },
  {
    id: '6',
    name: 'Roberto Alves',
    email: 'roberto@construtora.com',
    phone: '(61) 96655-4433',
    company: 'Construtora Base',
    status: 'Ativo',
    avatar: 'https://img.usecurling.com/ppl/thumbnail?gender=male&seed=6',
    createdAt: '2023-08-15T08:30:00Z',
  },
]
